spring:
  thymeleaf:
    cache: false # Enable template caching.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    encoding: UTF-8 # Template encoding.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
  jpa:
    hibernate.ddl-auto: update
    database: oracle
  datasource:
    platform: oracle
    url: "jdbc:oracle:thin:@"
    username: dapresentaciones12
    password: sysview12
    driverClassName: "oracle.jdbc.OracleDriver"
    initialize: false

# LOGGING
logging:
  level:
    com.sysview: DEBUG # Log levels severity mapping. For instance `logging.level.org.springframework=DEBUG`
